services:
  selenium:
    image: selenium/standalone-firefox:latest
    container_name: selenium_firefox
    ports:
      - "4444:4444"
    networks:
      - app_network
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_MAX_INSTANCES=1
      - SE_NODE_TIMEOUT=180
      - SE_BROWSER_TIMEOUT=120
      - SE_GRID_TIMEOUT=180
    shm_size: 2g 
    
  app_news_extractor_yogonet_com:
    build:
      context: ./app_news_extractor_yogonet_com
      dockerfile: Dockerfile
    container_name: app_news_extractor_yogonet_com
    networks:
      - app_network
    depends_on:
      - selenium
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
    volumes:
      - ./app_news_extractor_yogonet_com:/app
      - ./logs:/app/Logs
      - ./credentials:/credentials
      - ./untils/:/app/untils/
networks:
  app_network:
    driver: bridge
