version: '3.8'

services:
  selenium:
    image: selenium/standalone-firefox:latest
    container_name: selenium_firefox
    ports:
      - "4444:4444"
    networks:
      - app_network
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_MAX_INSTANCES=1

  app_news_extractor_yogonet_com:
    build:
      context: ./app_news_extractor_yogonet_com
      dockerfile: Dockerfile
    container_name: app_news_extractor_yogonet_com
    networks:
      - app_network
    depends_on:
      - selenium
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
    volumes:
      - .:/app_news_extractor_yogonet_com

networks:
  app_network:
    driver: bridge
