FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


ENV GOOGLE_APPLICATION_CREDENTIALS="/credentials/BigQuery_credentials.json"

#CMD ["python", "main.py"]
